# Nouvelle clé pour le front-end
sonar.projectKey=Jubaaa44_Projet10-front
sonar.organization=projet10
sonar.projectName=Projet10 Front-end

sonar.sources=src
sonar.inclusions=**/*.js,**/*.ts,**/*.html,**/*.css,**/*.scss
sonar.exclusions=node_modules/**,**/*.spec.ts,**/*.test.ts,**/*.min.js,dist/**,coverage/**

sonar.typescript.file.suffixes=.ts,.tsx
sonar.javascript.file.suffixes=.js,.jsx

# Tests (si vous en avez)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Coverage (si vous générez des rapports de couverture)
sonar.typescript.lcov.reportPaths=coverage/lcov.info
