# Configuration SonarCloud
sonar.projectKey=projet10
sonar.organization=Jubaaa44

# Nom du projet (optionnel)
sonar.projectName=bobapp

# Sources Angular
sonar.sources=src

# Inclusions
sonar.inclusions=**/*.js,**/*.ts,**/*.html,**/*.css,**/*.scss

# Exclusions
sonar.exclusions=node_modules/**,**/*.spec.ts,**/*.test.ts,**/*.min.js,dist/**,coverage/**

# Configuration TypeScript/JavaScript
sonar.typescript.file.suffixes=.ts,.tsx
sonar.javascript.file.suffixes=.js,.jsx

# Tests (si vous en avez)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Coverage (si vous générez des rapports de couverture)
sonar.typescript.lcov.reportPaths=coverage/lcov.info
