name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # Pour permettre l'exécution manuelle

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      
      - name: Verify token availability
        run: |
          if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "✅ SONAR_TOKEN is configured correctly"
          else
            echo "❌ SONAR_TOKEN is NOT configured"
            exit 1  # Cette ligne arrêtera le workflow si le token n'est pas configuré
          fi
      
      - name: Build and analyze
        run: |
          cd back
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Jubaaa44_Projet10 \
            -Dsonar.organization=projet10 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"