name: Code Quality Workflow

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  java-quality:
    name: Java Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        # Suppression du cache
    
    # Analyse avec Maven
    - name: Run Maven build with checks
      run: |
        cd back
        mvn clean install
      
    # Installation et exécution de PMD simplifié
    - name: Run PMD
      run: |
        cd back
        mvn pmd:pmd
      continue-on-error: true
    
    # Exécution de tests de sécurité simplifié
    - name: Run OWASP dependency check
      run: |
        cd back
        mvn dependency-check:check
      continue-on-error: true

  typescript-quality:
    name: TypeScript Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        # Suppression du cache
    
    - name: Install dependencies
      run: |
        cd front
        npm install
    
    # Exécuter les tests avec couverture
    - name: Run tests with coverage
      run: |
        cd front
        npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless
      continue-on-error: true
    
    # Audit de sécurité npm simplifié
    - name: Run npm audit
      run: |
        cd front
        npm audit || true

  # Étape simple pour indiquer que tout est terminé
  summary:
    name: Quality Summary
    needs: [java-quality, typescript-quality]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Quality checks completed
      run: echo "All quality checks have been completed. Check individual job logs for details."