name: Code Quality Workflow

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]
  schedule:
    - cron: '0 2 * * 1'  # Exécuter à 2h00 tous les lundis
  workflow_dispatch:  # Permettre le déclenchement manuel

jobs:
  java-quality:
    name: Java Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Historique complet pour SonarQube
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Analyse PMD pour règles de qualité Java
    - name: Run PMD
      run: mvn pmd:pmd
      working-directory: ./back
    
    # Analyse Checkstyle pour convention de code Java
    - name: Run Checkstyle
      run: mvn checkstyle:check
      continue-on-error: true
      working-directory: ./back
    
    # Rapport JaCoCo pour la couverture de code
    - name: Generate JaCoCo Report
      run: mvn clean verify jacoco:report
      working-directory: ./back
    
    # Analyse de vulnérabilités des dépendances
    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
      continue-on-error: true
      working-directory: ./back
    
    # Analyse SonarQube (optionnel - nécessite un serveur SonarQube)
    - name: SonarQube Scan
      if: ${{ false }}  # Désactivé par défaut - activer si vous avez un serveur SonarQube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn sonar:sonar
      working-directory: ./back
    
    # Archiver les rapports de qualité
    - name: Archive Java quality reports
      uses: actions/upload-artifact@v3
      with:
        name: java-quality-reports
        path: |
          back/target/site/jacoco/
          back/target/pmd.xml
          back/target/checkstyle-result.xml
          back/target/dependency-check-report.html
        retention-days: 7

  typescript-quality:
    name: TypeScript Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./front
    
    # Analyse ESLint pour TypeScript/Angular
    - name: Run ESLint
      run: npx eslint . --ext .ts
      continue-on-error: true
      working-directory: ./front
    
    # Tests et couverture de code
    - name: Run tests with coverage
      run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless
      working-directory: ./front
    
    # Audit des vulnérabilités npm
    - name: Run npm audit
      run: npm audit --json > npm-audit.json || true
      working-directory: ./front
    
    # Archiver les rapports de qualité
    - name: Archive TypeScript quality reports
      uses: actions/upload-artifact@v3
      with:
        name: typescript-quality-reports
        path: |
          front/coverage/
          front/npm-audit.json
        retention-days: 7

  quality-summary:
    name: Quality Summary
    needs: [java-quality, typescript-quality]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Download quality reports
      uses: actions/download-artifact@v3
      with:
        path: quality-reports
    
    - name: Generate quality summary
      run: |
        echo "# Code Quality Summary" > quality-summary.md
        echo "## Java Code Quality" >> quality-summary.md
        
        # JaCoCo Coverage Analysis
        if [ -f "quality-reports/java-quality-reports/jacoco/index.html" ]; then
          COVERAGE=$(grep -o "Total[^%]*%" quality-reports/java-quality-reports/jacoco/index.html | head -1 | tr -d " \t\n\r")
          if [ ! -z "$COVERAGE" ]; then
            echo "- Code Coverage: $COVERAGE" >> quality-summary.md
          else
            echo "- Code Coverage: Not available" >> quality-summary.md
          fi
        else
          echo "- Code Coverage: Report not found" >> quality-summary.md
        fi
        
        # PMD Issues
        if [ -f "quality-reports/java-quality-reports/pmd.xml" ]; then
          PMD_ISSUES=$(grep -c "<violation" quality-reports/java-quality-reports/pmd.xml || echo 0)
          echo "- PMD Issues: $PMD_ISSUES" >> quality-summary.md
        else
          echo "- PMD Issues: Report not found" >> quality-summary.md
        fi
        
        # Checkstyle Issues
        if [ -f "quality-reports/java-quality-reports/checkstyle-result.xml" ]; then
          CHECKSTYLE_ISSUES=$(grep -c "<error" quality-reports/java-quality-reports/checkstyle-result.xml || echo 0)
          echo "- Checkstyle Issues: $CHECKSTYLE_ISSUES" >> quality-summary.md
        else
          echo "- Checkstyle Issues: Report not found" >> quality-summary.md
        fi
        
        # OWASP Dependency Check
        if [ -f "quality-reports/java-quality-reports/dependency-check-report.html" ]; then
          VULNERABILITIES=$(grep -o "One or more dependencies were identified with [^<]*vulnerabilities" quality-reports/java-quality-reports/dependency-check-report.html | grep -o "[0-9]* vulnerabilities" || echo "0 vulnerabilities")
          echo "- Dependencies: $VULNERABILITIES" >> quality-summary.md
        else
          echo "- Dependencies: Report not found" >> quality-summary.md
        fi
        
        echo "## TypeScript/Angular Code Quality" >> quality-summary.md
        
        # Frontend Coverage
        if [ -f "quality-reports/typescript-quality-reports/coverage/index.html" ]; then
          TS_COVERAGE=$(grep -o "statements.*%" quality-reports/typescript-quality-reports/coverage/index.html | head -1 | grep -o "[0-9]*\.[0-9]*%" || echo "Not available")
          echo "- Code Coverage: $TS_COVERAGE" >> quality-summary.md
        else
          echo "- Code Coverage: Report not found" >> quality-summary.md
        fi
        
        # npm audit
        if [ -f "quality-reports/typescript-quality-reports/npm-audit.json" ]; then
          NPM_VULNERABILITIES=$(grep -o '"vulnerabilities": {[^}]*}' quality-reports/typescript-quality-reports/npm-audit.json | grep -o '"[^"]*": [0-9]*' | grep -v "info" | awk '{sum+=$2} END {print sum}' || echo 0)
          echo "- npm Vulnerabilities: $NPM_VULNERABILITIES" >> quality-summary.md
        else
          echo "- npm Vulnerabilities: Report not found" >> quality-summary.md
        fi
        
        echo "## Quality Thresholds" >> quality-summary.md
        echo "- Java Coverage: Target > 80%" >> quality-summary.md
        echo "- TypeScript Coverage: Target > 80%" >> quality-summary.md
        echo "- Zero critical vulnerabilities" >> quality-summary.md
        
        cat quality-summary.md
    
    - name: Upload quality summary
      uses: actions/upload-artifact@v3
      with:
        name: quality-summary
        path: quality-summary.md
        retention-days: 7
    
    # Si c'est une pull request, ajouter un commentaire avec le résumé de qualité
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('quality-summary.md', 'utf8');
          const context = github.context;
          
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });