name: Direct Token SonarCloud Analysis

on:
  workflow_dispatch:  # Exécution manuelle uniquement pour tester

jobs:
  sonarcloud:
    name: SonarCloud with Direct Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build backend
        run: |
          cd back
          mvn clean verify
      
      # IMPORTANT: Cette étape vous demandera de saisir le token directement
      # lors de l'exécution manuelle du workflow
      - name: Run SonarCloud with manual token input
        run: |
          cd back
          
          # Utilisez votre token SonarCloud ici directement (seulement pour tester)
          # Remplacez "votre_token_sonar_ici" par votre vrai token SonarCloud
          DIRECT_TOKEN="${{ inputs.sonar_token }}"
          
          if [ -z "$DIRECT_TOKEN" ]; then
            echo "WARNING: Direct token is empty, trying with embedded token"
            # Pour un test final, vous pouvez mettre votre token directement ici
            # MAIS ATTENTION: Ne commitez jamais ce fichier avec un vrai token!
            # Ceci est seulement pour le débogage
            DIRECT_TOKEN="f07127298efe92f902613a62c80f23f1a511291"
          fi
          
          echo "Using direct token input for SonarCloud analysis"
          
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Jubaaa44_Projet10 \
            -Dsonar.organization=projet10 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$DIRECT_TOKEN
    
    # Cette partie permet de fournir manuellement le token lors de l'exécution
    # du workflow
    inputs:
      sonar_token:
        description: 'SonarCloud Token'
        required: true