name: Simple SonarCloud Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build backend
        run: |
          cd back
          mvn clean verify
      
      - name: Print environment for debugging
        run: |
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Files in back directory:"
          ls -la back
      
      # Définir explicitement le token comme variable d'environnement
      - name: Set SonarCloud token
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
      
      # Utiliser Maven directement pour l'analyse Sonar
      - name: Run SonarCloud analysis with Maven
        run: |
          cd back
          export SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
          
          if [ -z "$SONAR_TOKEN" ]; then
            echo "ERROR: SONAR_TOKEN is empty!"
            exit 1
          else
            echo "SONAR_TOKEN is set (value hidden for security)"
          fi
          
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Jubaaa44_Projet10 \
            -Dsonar.organization=projet10 \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}