name: Exécution Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Run backend tests
      run: |
        cd back
        mvn clean install
        mvn clean verify
    
    # Archiver les rapports de test backend
    - name: Archive backend test reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: backend-test-reports
        path: |
          back/target/surefire-reports/
          back/target/site/jacoco/
  
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        # Suppression de l'option cache pour éviter les erreurs 422
    
    - name: Install Chrome for Karma tests
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies and run tests
      run: |
        cd front
        npm install
        npm run test -- --no-watch --browsers=ChromeHeadless
    
    # Archiver les rapports de test frontend
    - name: Archive frontend test reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: frontend-test-reports
        path: |
          front/coverage/