name: Tests Workflow

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        # Suppression du cache
    
    - name: Run backend tests
      run: |
        cd back
        mvn clean install
        mvn clean verify
  
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        # Suppression du cache
    
    - name: Install Chrome for Karma tests
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies and run tests
      run: |
        cd front
        npm install
        npm run test -- --no-watch --browsers=ChromeHeadless

  # Étape simple pour indiquer que tout est terminé
  summary:
    name: Test Summary
    needs: [backend-tests, frontend-tests]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Tests completed
      run: echo "All tests have been completed. Check individual job logs for details."