name: Exécution Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Run backend tests
      run: |
        cd back
        mvn clean install
        mvn clean verify
    
    # Création d'une archive des rapports
    - name: Create backend test report archive
      if: always()
      run: |
        mkdir -p test-reports
        cp -r back/target/surefire-reports test-reports/ || echo "No surefire reports found"
        cp -r back/target/site/jacoco test-reports/ || echo "No JaCoCo reports found"
        tar -czf backend-test-reports.tar.gz test-reports
        echo "Backend test reports archived in backend-test-reports.tar.gz"
        ls -la *.tar.gz
  
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Chrome for Karma tests
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies and run tests
      run: |
        cd front
        npm install
        npm run test -- --no-watch --browsers=ChromeHeadless
    
    # Création d'une archive des rapports
    - name: Create frontend test report archive
      if: always()
      run: |
        mkdir -p test-reports
        cp -r front/coverage test-reports/ || echo "No coverage reports found"
        tar -czf frontend-test-reports.tar.gz test-reports
        echo "Frontend test reports archived in frontend-test-reports.tar.gz"
        ls -la *.tar.gz